# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattleandpoultry',
            name='cattle',
            field=models.PositiveIntegerField(verbose_name='Велика рогата худоба'),
        ),
        migrations.AlterField(
            model_name='cattleandpoultry',
            name='horses',
            field=models.PositiveIntegerField(verbose_name='Коні'),
        ),
        migrations.AlterField(
            model_name='cattleandpoultry',
            name='pigs',
            field=models.PositiveIntegerField(verbose_name='Свині'),
        ),
        migrations.AlterField(
            model_name='cattleandpoultry',
            name='poultr',
            field=models.PositiveIntegerField(verbose_name='Птиця всіх видів'),
        ),
        migrations.AlterField(
            model_name='cattleandpoultry',
            name='sheep_goat',
            field=models.PositiveIntegerField(verbose_name='Вівці та кози'),
        ),
    ]
