# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_auto_20160603_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respondent',
            name='actual_adress_id',
        ),
        migrations.RemoveField(
            model_name='respondent',
            name='business_adress_id',
        ),
        migrations.AddField(
            model_name='respondent',
            name='actual_adress',
            field=models.CharField(default='New phys adress', max_length=45, verbose_name='Адреса здійснення діяльності'),
        ),
        migrations.AddField(
            model_name='respondent',
            name='business_adress',
            field=models.CharField(default='New adress', max_length=45, verbose_name='Місцезнаходження'),
        ),
    ]
