# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_auto_20160603_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='actual_adress',
            field=models.CharField(default='Там', max_length=45, verbose_name='Адреса здійснення діяльності'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='business_adress',
            field=models.CharField(default='Где-то', max_length=45, verbose_name='Місцезнаходження'),
        ),
    ]
