# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0004_auto_20160603_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cattleandpoultry',
            name='cattle',
            field=models.PositiveIntegerField(verbose_name='Cattle'),
        ),
        migrations.AlterField(
            model_name='cattleandpoultry',
            name='horses',
            field=models.PositiveIntegerField(verbose_name='Horses'),
        ),
        migrations.AlterField(
            model_name='cattleandpoultry',
            name='pigs',
            field=models.PositiveIntegerField(verbose_name='Pig'),
        ),
        migrations.AlterField(
            model_name='cattleandpoultry',
            name='poultr',
            field=models.PositiveIntegerField(verbose_name='Poutry'),
        ),
        migrations.AlterField(
            model_name='cattleandpoultry',
            name='sheep_goat',
            field=models.PositiveIntegerField(verbose_name='Sheep and goat'),
        ),
        migrations.AlterField(
            model_name='livestockproduction',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='livestockproduction',
            name='name',
            field=models.CharField(max_length=45, primary_key=True, serialize=False, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='livestockproduction',
            name='unit',
            field=models.CharField(max_length=45, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='poultry',
            name='adult',
            field=models.PositiveIntegerField(verbose_name='Adult'),
        ),
        migrations.AlterField(
            model_name='poultry',
            name='name',
            field=models.CharField(max_length=45, primary_key=True, serialize=False, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='poultry',
            name='young',
            field=models.PositiveIntegerField(verbose_name='Young'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='actual_adress',
            field=models.CharField(default='Somewhere else?', max_length=45, verbose_name='Physical adress'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='business_adress',
            field=models.CharField(default='Somewhere', max_length=45, verbose_name='Judicatl location'),
        ),
        migrations.AlterField(
            model_name='respondent',
            name='name',
            field=models.CharField(max_length=45, primary_key=True, serialize=False, verbose_name='Name'),
        ),
    ]
