# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0005_auto_20160603_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respondent',
            name='business_adress',
            field=models.CharField(default='Somewhere', max_length=45, verbose_name='Judical location'),
        ),
    ]
